export const CHANGE_FAVORITE_MOVIES = "CHANGE_FAVORITE_MOVIES"

export const CHANGE_HOME_PAGE = "CHANGE_HOME_PAGE"

export const CHANGE_UPCOMING_PAGE = "CHANGE_UPCOMING_PAGE"

export const CHANGE_UPCOMING_PAGE_NUMS = "CHANGE_UPCOMING_PAGE_NUMS"

export const CHANGE_MOVIE_PAGE_NUMS = "CHANGE_MOVIE_PAGE_NUMS"

export const CHANGE_UPCOMING_CURRENT_PAGE = "CHANGE_UPCOMING_CURRENT_PAGE"

export const CHANGE_MOVIE_CURRENT_PAGE = "CHANGE_MOVIE_CURRENT_PAGE"

export const CHANGE_WATCH_LISTS = "CHANGE_WATCH_LISTS"

export const ADD_FAVOR_REVIEWS = "ADD_FAVOR_REVIEWS"

export const ADD_WATCHLIST_REVIEWS = "ADD_WATCHLIST_REVIEWS"
