export const CHANGE_FAVORITE_MOVIES = "CHANGE_FAVORITE_MOVIES"

export const CHANGE_HOME_PAGE = "CHANGE_HOME_PAGE"

export const CHANGE_UPCOMING_PAGE = "CHANGE_UPCOMING_PAGE"

export const CHANGE_UPCOMING_PAGE_NUMS = "CHANGE_UPCOMING_PAGE_NUMS"

export const CHANGE_MOVIE_PAGE_NUMS = "CHANGE_MOVIE_PAGE_NUMS"

export const CHANGE_UPCOMING_CURRENT_PAGE = "CHANGE_UPCOMING_CURRENT_PAGE"

export const CHANGE_MOVIE_CURRENT_PAGE = "CHANGE_MOVIE_CURRENT_PAGE"