# Node docker image with Cypress and Chrome pre-installed
image: cypress/browsers:node12.0.0-chrome73

# Pipeline
stages:
  - install
  - build
  - prod_test
  - devel_test

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key:
    files:
      - package.json
  paths:
    - .npm
    - cache/Cypress
    - node_modules

# Jobs 

install_dependencies:
  stage: install
  only: 
    - staging
  script:
    - npm ci

bundle_app:
  stage: build
  only: 
    - staging
  script:
    - npm run build
  artifacts:
    paths:
      - build/

production_test:    
  stage: prod_test
  only:
    - staging
  before_script:
    - npm install -g http-server
    - npm install cypress
  script:
    # start the server in the background
    - npm run start:ci

development_test:
  stage: devel_test
  only:
    - staging
  script:
    - npm run cypress:run
    - npx nyc report --check-coverage --lines 80
  artifacts:
    when: always
    paths:
      - coverage
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 10 days



