export const CHANGE_TODAY_TVS = "CHANGE_TODAY_TVS"

export const CHANGE_LATEST_TVS = "CHANGE_LATEST_TVS"

export const CHANGE_HOT_TVS = "CHANGE_HOT_TVS"

export const CHANGE_POPULAR_TVS = "CHANGE_POPULAR_TVS"

export const CHANGE_TOPRATED_TVS = "CHANGE_TOPRATED_TVS"

export const CHANGE_SEARCH_TVS = "CHANGE_SEARCH_TVS"