export const CHANGE_TODAY_TVS = "CHANGE_TODAY_TVS"

export const CHANGE_LATEST_TVS = "CHANGE_LATEST_TVS"

export const CHANGE_HOT_TVS = "CHANGE_HOT_TVS"

export const CHANGE_TODAY_TVS_BY_SORT = "CHANGE_TODAY_TVS_BY_SORT"
